/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buysell;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author l2pc203m
 */
public class ProductBuySell extends javax.swing.JFrame {
    
    ProductInfo n = new ProductInfo();

    /**
     * Creates new form ProductBuySell
     */
    public ProductBuySell() {
        initComponents();
        initProduct();
    }
    
    public void initProduct(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buysell", "root", "apcl123456");
            PreparedStatement ps = con.prepareStatement("SELECT* FROM product");
            
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Integer i1 = rs.getInt(1);
                item.addItem(i1.toString());
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        up = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        qnt = new javax.swing.JTextField();
        item = new javax.swing.JComboBox<>();
        btnSell = new javax.swing.JButton();
        btnBuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monirul Islam");

        jLabel1.setText("TID:");

        jLabel2.setText("Product ID:");

        jLabel3.setText("Stock:");

        jLabel4.setText("Product name:");

        jLabel5.setText("Unit price:");

        jLabel6.setText("Total price:");

        jLabel7.setText("Quantity:");

        qnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qntKeyReleased(evt);
            }
        });

        item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select item" }));
        item.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemItemStateChanged(evt);
            }
        });

        btnSell.setText("Sell");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(btnSell)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(stk, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pn, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(item, javax.swing.GroupLayout.Alignment.LEADING, 0, 228, Short.MAX_VALUE)
                                .addComponent(tid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(up)
                                .addComponent(qnt)
                                .addComponent(tp))
                            .addComponent(btnBuy))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(stk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(qnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSell)
                    .addComponent(btnBuy))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void qntKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qntKeyReleased
        // TODO add your handling code here:
        String s1 = up.getText();
        double d1 = Double.parseDouble(s1);
        String s2 = qnt.getText();
        double d2 = Double.parseDouble(s2);
        double d3 = d1*d2;
        String s3 = String.valueOf(d3);
        tp.setText(s3);
    }//GEN-LAST:event_qntKeyReleased

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        // TODO add your handling code here:
        String s1 = tid.getText();
        Integer i1 = Integer.parseInt(s1);
        
        String s2 = item.getSelectedItem().toString();
        Integer i2 = Integer.parseInt(s2);
        
        String s3 = pn.getText();
        
        String s4 = stk.getText();
        Integer i3 = Integer.parseInt(s4);
        
        String s5 = up.getText();
        Double d1 = Double.parseDouble(s5);
        
        String s6 = qnt.getText();
        Integer i4 = Integer.parseInt(s6);
        
        String s7 = tp.getText();
        Double d2 = Double.parseDouble(s7);
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buysell", "root", "apcl123456");
            PreparedStatement ps = con.prepareStatement("INSERT INTO transaction(tid,pid,pname,stock,uprice,quantity,tprice,type) VALUES(?,?,?,?,?,?,?,?)");
            
            ps.setInt(1, i1);
            ps.setInt(2, i2);
            ps.setString(3, s3);
            ps.setInt(4, i3);
            ps.setDouble(5, d1);
            ps.setInt(6, i4);
            ps.setDouble(7, d2);
            ps.setString(8, "Sell");
            
            int i = ps.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null, "Data inserted !");
            }
           
        }catch(Exception e){
            e.printStackTrace();
        }
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buysell", "root", "apcl123456");
            PreparedStatement pst = con.prepareStatement("UPDATE product SET stock=? WHERE pid=?");
            
            String s8 = stk.getText();
            Integer i5 = Integer.parseInt(s8);
            String s9 = qnt.getText();
            Integer i6 = Integer.parseInt(s9);
            int i7 = i5-i6;
            String s10 = String.valueOf(i7);
            pst.setString(1, s10);
            
            String s11 = item.getSelectedItem().toString();
            pst.setString(2, s11);
            
            int x = pst.executeUpdate();
            if(x>0){
                stk.setText(s10);
                JOptionPane.showMessageDialog(null, "product updated !");
            }
           
        }catch(Exception e){
            e.printStackTrace();
        }
        
        String m1 = tid.getText();
        String m2 = item.getSelectedItem().toString();
        String m3 = pn.getText();
        String m4 = stk.getText();
        String m5 = up.getText();
        String m6 = qnt.getText();
        String m7 = tp.getText();
        
         n.setVisible(true);
        n.m("TID:  "+m1+
                "\nProduct ID:  "+m2+
                "\nProduct name:  "+m3+
                "\nStock:  "+m4+
                "\nUnit price:  "+m5+
                "\nQunatity:  "+m6+
                "\nTotal price:  "+m7
        );
         hide();
    }//GEN-LAST:event_btnSellActionPerformed

    private void itemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemItemStateChanged
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buysell", "root", "apcl123456");
            PreparedStatement ps = con.prepareStatement("SELECT* FROM product WHERE pid=?");
            
            String s1 =  item.getSelectedItem().toString();
            ps.setString(1, s1);
            
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                String s2 = rs.getString(2);
                pn.setText(s2);
                Integer i1=  rs.getInt(3);
                stk.setText(i1.toString());
                Double d1 = rs.getDouble(4);
                up.setText(d1.toString());
            }
        }catch(Exception e){
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_itemItemStateChanged

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        String s1 = tid.getText();
        Integer i1 = Integer.parseInt(s1);
        
        String s2 = item.getSelectedItem().toString();
        Integer i2 = Integer.parseInt(s2);
        
        String s3 = pn.getText();
        
        String s4 = stk.getText();
        Integer i3 = Integer.parseInt(s4);
        
        String s5 = up.getText();
        Double d1 = Double.parseDouble(s5);
        
        String s6 = qnt.getText();
        Integer i4 = Integer.parseInt(s6);
        
        String s7 = tp.getText();
        Double d2 = Double.parseDouble(s7);
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buysell", "root", "apcl123456");
            PreparedStatement ps = con.prepareStatement("INSERT INTO transaction(tid,pid,pname,stock,uprice,quantity,tprice,type) VALUES(?,?,?,?,?,?,?,?)");
            
            ps.setInt(1, i1);
            ps.setInt(2, i2);
            ps.setString(3, s3);
            ps.setInt(4, i3);
            ps.setDouble(5, d1);
            ps.setInt(6, i4);
            ps.setDouble(7, d2);
            ps.setString(8, "Buy");
            
            int i = ps.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null, "Data inserted !");
            }
           
        }catch(Exception e){
            e.printStackTrace();
        }
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buysell", "root", "apcl123456");
            PreparedStatement pst = con.prepareStatement("UPDATE product SET stock=? WHERE pid=?");
            
            String s8 = stk.getText();
            Integer i5 = Integer.parseInt(s8);
            String s9 = qnt.getText();
            Integer i6 = Integer.parseInt(s9);
            int i7 = i5+i6;
            String s10 = String.valueOf(i7);
            pst.setString(1, s10);
            
            String s11 = item.getSelectedItem().toString();
            pst.setString(2, s11);
            
            int x = pst.executeUpdate();
            if(x>0){
                stk.setText(s10);
                JOptionPane.showMessageDialog(null, "product updated !");
            }
           
        }catch(Exception e){
            e.printStackTrace();
        }
        
        String m1 = tid.getText();
        String m2 = item.getSelectedItem().toString();
        String m3 = pn.getText();
        String m4 = stk.getText();
        String m5 = up.getText();
        String m6 = qnt.getText();
        String m7 = tp.getText();
        n.setVisible(true);
       n.m("TID:  "+m1+
                "\nProduct ID:  "+m2+
                "\nProduct name:  "+m3+
                "\nStock:  "+m4+
                "\nUnit price:  "+m5+
                "\nQunatity:  "+m6+
                "\nTotal price:  "+m7
        );
        hide();
    }//GEN-LAST:event_btnBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductBuySell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductBuySell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductBuySell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductBuySell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductBuySell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnSell;
    private javax.swing.JComboBox<String> item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField qnt;
    private javax.swing.JTextField stk;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tp;
    private javax.swing.JTextField up;
    // End of variables declaration//GEN-END:variables
}
