/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clock;

import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
/**
 *
 * @author R-one
 */
public class AlarmClock extends javax.swing.JFrame {
    
    AlarmText n = new AlarmText();
    int timeRun = 0;

    /**
     * Creates new form AlarmClock
     */
    public AlarmClock() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        new Thread(){
            public void run(){
                while(timeRun==0){
                    Calendar cal = new GregorianCalendar();
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    int amPm = cal.get(Calendar.AM_PM);
                    int d = cal.get(Calendar.DAY_OF_WEEK);
                    String d1 = "";
                    if(d==1){
                       d1 = "Sunday"; 
                    }
                    if(d==2){
                       d1 = "Monday"; 
                    }
                    if(d==3){
                       d1 = "Tuesday"; 
                    }
                    if(d==4){
                       d1 = "Wednesday"; 
                    }
                    if(d==5){
                       d1 = "Thursday"; 
                    }
                    if(d==6){
                       d1 = "Friday"; 
                    }
                    if(d==7){
                       d1 = "Saturday"; 
                    }
                    String day_night = "";
                    if(amPm==1){
                        day_night = "PM";
                    }else{
                        day_night = "AM";
                    }
                    String h = String.valueOf(hour);
                    String m = String.valueOf(min);
                    String s = String.valueOf(sec);
                    
                    if(hour<10){
                        h = "0"+h;
                    }
                    if(hour==00){
                        h="12";
                    }
                    if(min<10){
                        m = "0"+m;
                    }
                    if(sec<10){
                        s = "0"+s;
                    }
                    String time = h + " : " + m + " : " + s + " " + day_night;
                    clock.setText(time);
                    days.setText(d1);
                    
                    if((hour==01)&&(min==00)&&(sec==00)&&(day_night=="PM")){
                        //JOptionPane.showMessageDialog(null, "It's time to--\nGO HOME !","Monirul Islam",JOptionPane.WARNING_MESSAGE);
                        n.setVisible(true);
                        
                    }
                }
                
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clock = new javax.swing.JLabel();
        days = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alarm Clock");
        setResizable(false);

        clock.setBackground(new java.awt.Color(255, 51, 0));
        clock.setFont(new java.awt.Font("Digital-7", 0, 76)); // NOI18N
        clock.setForeground(new java.awt.Color(153, 255, 51));
        clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        days.setFont(new java.awt.Font("Shruti", 1, 18)); // NOI18N
        days.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(days, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(days, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlarmClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlarmClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlarmClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlarmClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlarmClock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clock;
    private javax.swing.JLabel days;
    // End of variables declaration//GEN-END:variables
}
