/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package product;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author l2pc211m
 */
public class ProductPrice extends javax.swing.JFrame {

    /**
     * Creates new form ProductPrice
     */
    public ProductPrice() {
        initComponents();
        initProduct();
    }
    
    public void initProduct(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/monirul2", "root", "apcl123456");
            PreparedStatement ps = con.prepareStatement("SELECT* FROM product");
            //String s1 = item.getSelectedItem().toString();
            
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Integer i1 = rs.getInt(1);
                String i2 = String.valueOf(i1);
                item.addItem(i2);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        stk = new javax.swing.JTextField();
        tp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        up = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        qnt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        item = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        btnSell = new javax.swing.JButton();
        btnBuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TID:");

        jLabel2.setText("Product ID:");

        jLabel3.setText("Product name:");

        jLabel4.setText("Stock:");

        jLabel5.setText("Unit price:");

        jLabel6.setText("Quantity:");

        qnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qntKeyReleased(evt);
            }
        });

        jLabel7.setText("Total price:");

        item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select item" }));
        item.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemItemStateChanged(evt);
            }
        });
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActionPerformed(evt);
            }
        });

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        btnSell.setText("Sell");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(88, 88, 88)
                        .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qnt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stk, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSell)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuy)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(stk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(qnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSell)
                    .addComponent(btnBuy))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void qntKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qntKeyReleased
        // TODO add your handling code here:
        String s1 = up.getText();
        double d1 = Double.parseDouble(s1);
        String s2 = qnt.getText();
        double d2 = Double.parseDouble(s2);
        double d3 = d1*d2;
        String s3 = String.valueOf(d3);
        tp.setText(s3);
    }//GEN-LAST:event_qntKeyReleased

    private void itemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemItemStateChanged
        // TODO add your handling code here:
        if(item.getSelectedItem().toString().equals("Select item")){
            tid.setText("");
            pn.setText("");
            stk.setText("");
            qnt.setText("");
            up.setText("");
            tp.setText("");
        }
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/monirul2", "root", "apcl123456");
            PreparedStatement ps = con.prepareStatement("SELECT* FROM product WHERE pid=?");
            
            String s1 = item.getSelectedItem().toString();
            ps.setString(1,s1);
            
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                String s2 = rs.getString(2);
                pn.setText(s2);
                Integer i1 = rs.getInt(3);
                stk.setText(String.valueOf(i1));
                Double d1 = rs.getDouble(4);
                up.setText(String.valueOf(d1));
               
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_itemItemStateChanged

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/monirul2", "root", "apcl123456");
            PreparedStatement ps = con.prepareStatement("INSERT INTO transaction(tid,pid,pname,stock,uprice,quantity,tprice,type) VALUES(?,?,?,?,?,?,?,?)");
            
            String s1 = tid.getText();
            ps.setString(1,s1);
            String s2 = item.getSelectedItem().toString();
            ps.setString(2, s2);
            String s3 = pn.getText();
            ps.setString(3, s3);
            String s4 = stk.getText();
            ps.setString(4, s4);
            String s5 = up.getText();
            ps.setString(5, s5);
            String s6 = qnt.getText();
            ps.setString(6, s6);
            String s7 = tp.getText();
            ps.setString(7, s7);
            ps.setString(8, "Sell");
            int i1 = ps.executeUpdate();
            if(i1>0){
                JOptionPane.showMessageDialog(null, "Data inserted !");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/monirul2", "root", "apcl123456");
            PreparedStatement ps1 = con.prepareStatement("UPDATE product SET stock=? WHERE pid=?");
            
           String s9 = stk.getText();
           int i2 = Integer.parseInt(s9);
           String s10 = qnt.getText();
           int i3 = Integer.parseInt(s10);
           int i4 = i2-i3;
           String s11 = String.valueOf(i4);
           ps1.setString(1, s11);
            
           String s20 = item.getSelectedItem().toString();
           ps1.setString(2, s20);
            
           int i5 = ps1.executeUpdate();
           if(i5>0){
               stk.setText(s11);
               JOptionPane.showMessageDialog(null, "product updated !");
           }
        }catch(Exception e){
            e.printStackTrace();
        }
        
         String m1 = tid.getText();
        String m2 = item.getSelectedItem().toString();
        String m3 = pn.getText();
        String m4 = stk.getText();
        String m5 = up.getText();
        String m6 = qnt.getText();
        String m7 = tp.getText();
        ta.setText("TID:  "+m1+
                "\nProduct ID:  "+m2+
                "\nProduct name:  "+m3+
                "\nStock:  "+m4+
                "\nUnit price:  "+m5+
                "\nQuantity:  "+m6+
                "\nTotal price:  "+m7
        );
    }//GEN-LAST:event_btnSellActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/monirul2", "root", "apcl123456");
            PreparedStatement ps = con.prepareStatement("INSERT INTO transaction(tid,pid,pname,stock,uprice,quantity,tprice,type) VALUES(?,?,?,?,?,?,?,?)");
            
            String s1 = tid.getText();
            ps.setString(1,s1);
            String s2 = item.getSelectedItem().toString();
            ps.setString(2, s2);
            String s3 = pn.getText();
            ps.setString(3, s3);
            String s4 = stk.getText();
            ps.setString(4, s4);
            String s5 = up.getText();
            ps.setString(5, s5);
            String s6 = qnt.getText();
            ps.setString(6, s6);
            String s7 = tp.getText();
            ps.setString(7, s7);
            ps.setString(8, "Buy");
            int i1 = ps.executeUpdate();
            if(i1>0){
                JOptionPane.showMessageDialog(null, "Data inserted !");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/monirul2", "root", "apcl123456");
            PreparedStatement ps1 = con.prepareStatement("UPDATE product SET stock=? WHERE pid=?");
            
           String s9 = stk.getText();
           int i2 = Integer.parseInt(s9);
           String s10 = qnt.getText();
           int i3 = Integer.parseInt(s10);
           int i4 = i2+i3;
           String s11 = String.valueOf(i4);
           ps1.setString(1, s11);
            
           String s20 = item.getSelectedItem().toString();
           ps1.setString(2, s20);
            
           int i5 = ps1.executeUpdate();
           if(i5>0){
               stk.setText(s11);
               JOptionPane.showMessageDialog(null, "product updated !");
           }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        String m1 = tid.getText();
        String m2 = item.getSelectedItem().toString();
        String m3 = pn.getText();
        String m4 = stk.getText();
        String m5 = up.getText();
        String m6 = qnt.getText();
        String m7 = tp.getText();
        ta.setText("TID:  "+m1+
                "\nProduct ID:  "+m2+
                "\nProduct name:  "+m3+
                "\nStock:  "+m4+
                "\nUnit price:  "+m5+
                "\nQuantity:  "+m6+
                "\nTotal price:  "+m7
        );
       
    }//GEN-LAST:event_btnBuyActionPerformed

    private void itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductPrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductPrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnSell;
    private javax.swing.JComboBox<String> item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField qnt;
    private javax.swing.JTextField stk;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tp;
    private javax.swing.JTextField up;
    // End of variables declaration//GEN-END:variables
}
